<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $session->name }}</title>
    <style>
        body { font-family: sans-serif; color: #1a1a1a; font-size: 14px; }
        h1 { font-size: 22px; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 4px; }
        .date { color: #666; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { border: 1px solid #ccc; padding: 8px 10px; text-align: left; }
        th { background: #1a1a1a; color: #fff; text-transform: uppercase; font-size: 11px; letter-spacing: 1px; }
        tr:nth-child(even) { background: #f5f5f0; }
        .footer { margin-top: 24px; font-size: 11px; color: #999; }
    </style>
</head>
<body>
    <h1>{{ $session->name }}</h1>
    <div class="date">{{ $session->performed_at->format('d M Y — H:i') }}</div>

    <table>
        <thead>
            <tr>
                <th>Exercise</th>
                <th>Sets</th>
                <th>Reps</th>
                <th>Weight (kg)</th>
                <th>Volume</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($session->rows as $row)
                <tr>
                    <td>{{ $row->exercise->name }}</td>
                    <td>{{ $row->sets }}</td>
                    <td>{{ $row->reps }}</td>
                    <td>{{ number_format($row->weight, 2) }}</td>
                    <td>{{ number_format($row->volume, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">Generated by Iron Log</div>
</body>
</html>
